// ponytail: shim — all exports moved to @vizteck/core
export {
  LessonEditor,
  LessonViewer,
  LessonPageShell,
  LessonPageLayout,
  CoverDisplay,
  BreadcrumbDisplay,
  PageTreeSidebar,
  PageTreeItem,
  SearchModal,
  useSearchModal,
  useSearch,
} from '@vizteck/core';
export type {
  LessonEditorProps,
  LessonViewerProps,
  LessonPageShellProps,
  LessonPageLayoutProps,
  CoverDisplayProps,
  BreadcrumbDisplayProps,
  PageTreeSidebarProps,
  PageTreeItemProps,
  SearchModalProps,
  TimeGroup,
  BreadcrumbItem,
  LessonShellNode,
  PageTreeNode,
  PageTree,
} from '@vizteck/core';
